### ISSUE TITLE
Bug: yt command crashes the application

### ISSUE THREAD

**Issue by sedlak477** [SirTrollsalot/Desktopcommands#1]
When entering the command `yt behind blue eyes` in file `Youtube.cs` on line `35` a `System.ArgumentException` is thorwn.  

### Stack Trace:
```
System.ArgumentException
  HResult=0x80070057
  Message=Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Desktopcommands.Commands.CommandUtilities.Youtube.SearchVideos(String term, Int32 maxresults) in C:\Users\Michael\Desktop\Desktopcommands-master\Desktopcommands\Commands\CommandUtilities\Youtube.cs:line 35
   at Desktopcommands.Commands.Command_Youtube.Execute() in C:\Users\Michael\Desktop\Desktopcommands-master\Desktopcommands\Commands\Command_Youtube.cs:line 32
   at Desktopcommands.Utilities.CommandExecuter.Execute(String input) in C:\Users\Michael\Desktop\Desktopcommands-master\Desktopcommands\Utilities\CommandExecuter.cs:line 25
   at Desktopcommands.MainWindow.HandleEnter(Object sender, KeyEventArgs e) in C:\Users\Michael\Desktop\Desktopcommands-master\Desktopcommands\MainWindow.xaml.cs:line 91
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Desktopcommands.App.Main()
```

**Comment by SirTrollsalot** [comment]
I found the problem and fixed it.
Thanks for helping improve my projekt.

**Comment by sedlak477** [comment]
no probleme
